### ISSUE TITLE
Please publish .env.sample file

### ISSUE THREAD

**Issue by gardner** [I-NERGY/DeepTSF#2]
Γειά σου!

Great work!

Please consider publishing an example `.env` file for the `docker-compose.yml`.

Thank you!

**Comment by gardner** [comment]
Additionally, the `load-forecasting-dashboard:0.1` container is missing. Is the code for that available?

**Comment by pelekhs** [comment]
Hello!

Thanks for creating the issue! We are up to some refinements on the application. We will come back with feedback by next week!
